name = "RationalMeatAxe"
uuid = "f91be322-f4fa-4c7a-81f8-273e4b273218"
authors = ["Markus Kurtz <kurtz@mathematik.uni-kl.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
